/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as MergeIndexRouteImport } from './routes/merge/index'
import { Route as ExtractorIndexRouteImport } from './routes/extractor/index'
import { Route as CalibrationIndexRouteImport } from './routes/calibration/index'
import { Route as AdvancedIndexRouteImport } from './routes/advanced/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const MergeIndexRoute = MergeIndexRouteImport.update({
  id: '/merge/',
  path: '/merge/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtractorIndexRoute = ExtractorIndexRouteImport.update({
  id: '/extractor/',
  path: '/extractor/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalibrationIndexRoute = CalibrationIndexRouteImport.update({
  id: '/calibration/',
  path: '/calibration/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvancedIndexRoute = AdvancedIndexRouteImport.update({
  id: '/advanced/',
  path: '/advanced/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advanced/': typeof AdvancedIndexRoute
  '/calibration/': typeof CalibrationIndexRoute
  '/extractor/': typeof ExtractorIndexRoute
  '/merge/': typeof MergeIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advanced': typeof AdvancedIndexRoute
  '/calibration': typeof CalibrationIndexRoute
  '/extractor': typeof ExtractorIndexRoute
  '/merge': typeof MergeIndexRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advanced/': typeof AdvancedIndexRoute
  '/calibration/': typeof CalibrationIndexRoute
  '/extractor/': typeof ExtractorIndexRoute
  '/merge/': typeof MergeIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/advanced/'
    | '/calibration/'
    | '/extractor/'
    | '/merge/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/advanced' | '/calibration' | '/extractor' | '/merge' | '/settings'
  id:
    | '__root__'
    | '/'
    | '/advanced/'
    | '/calibration/'
    | '/extractor/'
    | '/merge/'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdvancedIndexRoute: typeof AdvancedIndexRoute
  CalibrationIndexRoute: typeof CalibrationIndexRoute
  ExtractorIndexRoute: typeof ExtractorIndexRoute
  MergeIndexRoute: typeof MergeIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merge/': {
      id: '/merge/'
      path: '/merge'
      fullPath: '/merge/'
      preLoaderRoute: typeof MergeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extractor/': {
      id: '/extractor/'
      path: '/extractor'
      fullPath: '/extractor/'
      preLoaderRoute: typeof ExtractorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calibration/': {
      id: '/calibration/'
      path: '/calibration'
      fullPath: '/calibration/'
      preLoaderRoute: typeof CalibrationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advanced/': {
      id: '/advanced/'
      path: '/advanced'
      fullPath: '/advanced/'
      preLoaderRoute: typeof AdvancedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdvancedIndexRoute: AdvancedIndexRoute,
  CalibrationIndexRoute: CalibrationIndexRoute,
  ExtractorIndexRoute: ExtractorIndexRoute,
  MergeIndexRoute: MergeIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
